[package]
name = "atomic-cuckoo-filter"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_builder = "0.20"
parking_lot_core = "0.9"
rand = "0.9"
thiserror = "2.0"

[dev-dependencies]
ahash = "0.8"
cuckoofilter = "0.5"